### ISSUE TITLE
Which arm arch?

### ISSUE THREAD

**Issue by steffenschumacher** [sc0ty/nsa310-kernel#1]
Hi,

Sorry - complete newb, trying to climb mount everest here, but I'm trying to build a 4.9 kernel for my nsa310, and from the looks of things, it seems that this is well supported in kernel sources.
Could you give me quick pointers on what to watch out for?
I guess I'm using armhf right?
This seems to be working at least..
```
root@debian:/kernelbuild/linux-4.9# export CROSS_COMPILE=arm-linux-gnueabihf-
root@debian:/kernelbuild/linux-4.9# make -j6 zImage dtbs
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
```

**Comment by sc0ty** [comment]
I am using gnueabi complier (not hf), not sure if hardware floats are supported.
